# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkeKP2nMWBzw463o70xq5jmScXvSAeka
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf                     # TensorFlow: Google's machine learning framework
from tensorflow import keras               # Keras: user-friendly API built into TensorFlow
from tensorflow.keras.models import Sequential        # Sequential: builds models layer-by-layer
from tensorflow.keras.layers import Dense, Flatten    # Dense: fully connected layer
                                                       # Flatten: converts 2D image to 1D array
from tensorflow.keras.utils import to_categorical     # to_categorical: one-hot encoding tool
from tensorflow.keras.datasets import mnist            # mnist: the digit dataset
print("TensorFlow version:", tf.__version__)
# Set a random seed for reproducibility
# This ensures you get the same results each time you run the code
np.random.seed(42)
tf.random.set_seed(42)
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Let's examine what we received
print(f"Training images shape  : {x_train.shape}")
# Output: (60000, 28, 28) means 60,000 images, each 28 pixels tall, 28 pixels wide

print(f"Training labels shape  : {y_train.shape}")
# Output: (60000,) means 60,000 labels (one per image)

print(f"Testing images shape   : {x_test.shape}")
# Output: (10000, 28, 28) means 10,000 test images

print(f"Testing labels shape   : {y_test.shape}")
# Output: (10000,) means 10,000 test labels

print(f"\nPixel value range      : {x_train.min()} to {x_train.max()}")
# Output: 0 to 255 (standard grayscale: 0=black, 255=white)

print(f"Unique digit labels    : {np.unique(y_train)}")
# Output: [0 1 2 3 4 5 6 7 8 9] - the ten digits

fig, axes = plt.subplots(2, 5, figsize=(12, 5))
# Creates a figure with 2 rows and 5 columns = 10 image slots

fig.suptitle('Sample MNIST Handwritten Digits', fontsize=16, fontweight='bold')

for i, ax in enumerate(axes.flat):
    # axes.flat lets us loop through all 10 subplot positions
    ax.imshow(x_train[i], cmap='gray')      # Display image in grayscale
    ax.set_title(f'Label: {y_train[i]}', fontsize=12)  # Show the correct digit
    ax.axis('off')                            # Hide the axis lines and ticks

plt.tight_layout()        # Adjusts spacing so nothing overlaps
plt.savefig('sample_digits.png', dpi=150, bbox_inches='tight')
plt.show()
print("Sample digits plot saved as 'sample_digits.png'")

#   A) NORMALIZE pixel values
#   B) RESHAPE (flatten) images
#   C) ONE-HOT ENCODE labels

print("\n>>> STEP 3: Preprocessing Data...")

#A) NORMALIZATION

x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

print(f"After normalization - Pixel range: {x_train.min():.1f} to {x_train.max():.1f}")


#FLATTENING

x_train_flat = x_train.reshape(x_train.shape[0], 28 * 28)
x_test_flat = x_test.reshape(x_test.shape[0], 28 * 28)

print(f"After flattening - Training shape: {x_train_flat.shape}")
print(f"After flattening - Testing shape : {x_test_flat.shape}")

#ONE-HOT ENCODING LABELS
num_classes = 10    # Digits 0-9 = 10 classes
# Save original labels before encoding (we'll need them later)
y_train_original = y_train.copy()
y_test_original = y_test.copy()

y_train_encoded = to_categorical(y_train, num_classes)
y_test_encoded = to_categorical(y_test, num_classes)

print(f"\nBefore one-hot encoding - Label example: {y_train_original[0]}")
print(f"After one-hot encoding  - Label example: {y_train_encoded[0]}")
print(f"One-hot encoded shape   - Training: {y_train_encoded.shape}")
# Shape: (60000, 10) - each of the 60000 samples has a 10-element vector
# STEP 4: DEFINE THE NEURAL NETWORK ARCHITECTURE

# MODEL B - Sigmoid:
#   Formula: f(x) = 1 / (1 + e^(-x))
#   Squashes any input to a value between 0 and 1.
#   Pros: Smooth, bounded output
#   Cons: Can cause "vanishing gradients" (very slow learning in deep networks)
#
# NETWORK STRUCTURE (same for both models):
# ┌─────────────────┐
# │  Input Layer     │  784 neurons (one per pixel)
# │  (Flatten)       │
# ├─────────────────┤
# │  Hidden Layer 1  │  256 neurons with activation function
# ├─────────────────┤
# │  Hidden Layer 2  │  128 neurons with activation function
# ├─────────────────┤
# │  Hidden Layer 3  │  64 neurons with activation function
# ├─────────────────┤
# │  Output Layer    │  10 neurons (one per digit) with Softmax
# └─────────────────┘
#
# SOFTMAX (output layer): Converts raw scores into probabilities (0-1)
# that sum to 1. The highest probability = the predicted digit.

print("\n>>> STEP 4: Building Neural Network Models...")
print("-" * 60)


def build_model(activation_function, model_name):
    """
    Creates and compiles a neural network model.

    Parameters:
    -----------
    activation_function : str
        The activation function for hidden layers ('relu' or 'sigmoid')
    model_name : str
        A descriptive name for the model

    Returns:
    --------
    model : keras.Sequential
        The compiled (ready-to-train) neural network model
    """

    model = Sequential(name=model_name)
    # Sequential means layers are stacked one after another (like a sandwich)

    # --- Input Layer ---
    # Dense(256) = a fully connected layer with 256 neurons
    # input_shape=(784,) tells the network each input is a flat array of 784 values
    model.add(Dense(256,
                    activation=activation_function,
                    input_shape=(784,),
                    name='hidden_layer_1'))

    # --- Hidden Layer 2 ---
    # 128 neurons, same activation function
    # Note: we don't need input_shape here; Keras infers it from the previous layer
    model.add(Dense(128,
                    activation=activation_function,
                    name='hidden_layer_2'))

    # --- Hidden Layer 3 ---
    # 64 neurons, same activation function
    model.add(Dense(64,
                    activation=activation_function,
                    name='hidden_layer_3'))

    # --- Output Layer ---
    # 10 neurons (one for each digit 0-9)
    # Softmax activation: outputs probabilities that sum to 1
    # Example output: [0.01, 0.02, 0.05, 0.80, 0.01, 0.03, 0.02, 0.03, 0.02, 0.01]
    #                  means 80% confident it's digit "3"
    model.add(Dense(num_classes,
                    activation='softmax',
                    name='output_layer'))

    # --- Compile the Model ---
    # This configures the model for training by specifying:
    #
    # optimizer='adam':
    #   Adam is an advanced optimization algorithm that adjusts learning rate
    #   automatically. It's the most popular choice and works well in most cases.
    #
    # loss='categorical_crossentropy':
    #   This is the loss function - it measures how wrong our predictions are.
    #   'categorical_crossentropy' is designed for multi-class classification
    #   with one-hot encoded labels. Lower loss = better predictions.
    #
    # metrics=['accuracy']:
    #   We also want to track accuracy (% of correct predictions) during training.

    model.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    return model


# Build Model A: ReLU activation
print("\nBuilding Model A (ReLU activation)...")
model_relu = build_model('relu', 'Model_A_ReLU')

# Build Model B: Sigmoid activation
print("Building Model B (Sigmoid activation)...")
model_sigmoid = build_model('sigmoid', 'Model_B_Sigmoid')

# Display the architecture of both models
print("\n" + "=" * 60)
print("MODEL A - ReLU Architecture:")
print("=" * 60)
model_relu.summary()
# summary() shows: layer names, output shapes, and number of parameters
# Parameters = the weights the network learns during training

print("\n" + "=" * 60)
print("MODEL B - Sigmoid Architecture:")
print("=" * 60)
model_sigmoid.summary()

# Let's count total parameters to understand model complexity
total_params = model_relu.count_params()
print(f"\nTotal trainable parameters per model: {total_params:,}")
print("(Both models have identical structure, just different activation functions)")

# =====================================================================
# STEP 5: TRAIN BOTH MODELS
# =====================================================================
# Training = showing the network many examples so it learns the patterns.
#
# KEY TRAINING CONCEPTS:
#
# EPOCH: One complete pass through the ENTIRE training dataset.
#   Like reading a textbook cover-to-cover once = 1 epoch.
#   We'll do 20 epochs (read the textbook 20 times).
#
# BATCH SIZE: How many images the network sees before updating its weights.
#   batch_size=128 means: look at 128 images, calculate the average error,
#   then adjust weights. This is more efficient than updating after every
#   single image (too noisy) or after all 60,000 images (too slow).
#
# VALIDATION SPLIT: We reserve 20% of training data to check progress.
#   The network does NOT learn from validation data - it's like a mini-test
#   taken after each epoch to see if the network is truly learning
#   (not just memorizing).
#
# WHAT HAPPENS DURING TRAINING?
#   1. Forward pass: Data flows through the network, prediction is made
#   2. Loss calculation: Compare prediction to actual label
#   3. Backward pass: Calculate how to adjust weights to reduce loss
#   4. Weight update: Adjust weights using the optimizer (Adam)
#   Repeat for every batch, for every epoch.

print("\n>>> STEP 5: Training Both Models...")
print("-" * 60)

# Training hyperparameters (settings that control the training process)
EPOCHS = 20           # Number of times to go through the entire dataset
BATCH_SIZE = 128      # Number of samples per weight update
VALIDATION_SPLIT = 0.2  # 20% of training data used for validation

# ----- Train Model A: ReLU -----
print("\n" + "=" * 60)
print("TRAINING MODEL A (ReLU Activation)")
print("=" * 60)

history_relu = model_relu.fit(
    x_train_flat,           # Input: flattened training images
    y_train_encoded,        # Target: one-hot encoded labels
    epochs=EPOCHS,          # Number of training epochs
    batch_size=BATCH_SIZE,  # Samples per batch
    validation_split=VALIDATION_SPLIT,  # 20% for validation
    verbose=1               # verbose=1: show progress bar for each epoch
)
# The fit() function returns a 'history' object containing:
#   - history.history['accuracy']       : training accuracy per epoch
#   - history.history['val_accuracy']   : validation accuracy per epoch
#   - history.history['loss']           : training loss per epoch
#   - history.history['val_loss']       : validation loss per epoch

# ----- Train Model B: Sigmoid -----
print("\n" + "=" * 60)
print("TRAINING MODEL B (Sigmoid Activation)")
print("=" * 60)

history_sigmoid = model_sigmoid.fit(
    x_train_flat,
    y_train_encoded,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    validation_split=VALIDATION_SPLIT,
    verbose=1
)

print("\n✓ Both models trained successfully!")

# =====================================================================
# STEP 6: EVALUATE BOTH MODELS ON THE TEST SET
# =====================================================================
# Now we test both models on data they have NEVER seen before.
# This is the true measure of how well they learned.

print("\n>>> STEP 6: Evaluating Models on Test Set...")
print("-" * 60)

# Evaluate Model A (ReLU)
test_loss_relu, test_acc_relu = model_relu.evaluate(
    x_test_flat,        # Test images
    y_test_encoded,     # Test labels
    verbose=0           # verbose=0: don't print progress bar
)

# Evaluate Model B (Sigmoid)
test_loss_sigmoid, test_acc_sigmoid = model_sigmoid.evaluate(
    x_test_flat,
    y_test_encoded,
    verbose=0
)

# Print results in a formatted table
print("\n" + "=" * 60)
print("           FINAL TEST SET RESULTS")
print("=" * 60)
print(f"{'Metric':<25} {'ReLU':>12} {'Sigmoid':>12}")
print("-" * 60)
print(f"{'Test Accuracy':<25} {test_acc_relu:>11.4f} {test_acc_sigmoid:>11.4f}")
print(f"{'Test Accuracy (%)':<25} {test_acc_relu*100:>10.2f}% {test_acc_sigmoid*100:>10.2f}%")
print(f"{'Test Loss':<25} {test_loss_relu:>11.4f} {test_loss_sigmoid:>11.4f}")
print("=" * 60)

# =====================================================================
# STEP 7: VISUALIZE TRAINING PROGRESS (PLOTS)
# =====================================================================
# Plots help us understand HOW each model learned over time.
# We create two types of plots for each model:
#   1. Accuracy curves: Did the model get better at predicting?
#   2. Loss curves: Did the model's errors decrease?
#
# We plot BOTH training and validation curves because:
#   - If training accuracy is high but validation accuracy is low,
#     the model is OVERFITTING (memorizing, not learning).
#   - Ideally, both curves should rise together (accuracy) or
#     fall together (loss).

print("\n>>> STEP 7: Creating Performance Visualization Plots...")
print("-" * 60)

# Extract history data for easy plotting
epochs_range = range(1, EPOCHS + 1)  # x-axis: epoch numbers 1 to 20

# ReLU history data
relu_train_acc = history_relu.history['accuracy']
relu_val_acc = history_relu.history['val_accuracy']
relu_train_loss = history_relu.history['loss']
relu_val_loss = history_relu.history['val_loss']

# Sigmoid history data
sig_train_acc = history_sigmoid.history['accuracy']
sig_val_acc = history_sigmoid.history['val_accuracy']
sig_train_loss = history_sigmoid.history['loss']
sig_val_loss = history_sigmoid.history['val_loss']

# ==========================================
# PLOT SET 1: MODEL A (ReLU) - Individual Plots
# ==========================================

fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
fig1.suptitle('Model A: ReLU Activation - Training Progress',
              fontsize=16, fontweight='bold', y=1.02)

# --- Plot 1a: ReLU Accuracy ---
ax1.plot(epochs_range, relu_train_acc, 'b-o', linewidth=2,
         markersize=4, label='Training Accuracy', color='#2196F3')
ax1.plot(epochs_range, relu_val_acc, 'r-s', linewidth=2,
         markersize=4, label='Validation Accuracy', color='#F44336')
ax1.set_title('Accuracy over Epochs', fontsize=14, fontweight='bold')
ax1.set_xlabel('Epoch', fontsize=12)
ax1.set_ylabel('Accuracy', fontsize=12)
ax1.legend(fontsize=11, loc='lower right')
ax1.grid(True, alpha=0.3)                    # Light grid for readability
ax1.set_xlim(1, EPOCHS)
ax1.set_ylim(0.85, 1.0)                      # Zoom in to relevant range

# --- Plot 1b: ReLU Loss ---
ax2.plot(epochs_range, relu_train_loss, 'b-o', linewidth=2,
         markersize=4, label='Training Loss', color='#2196F3')
ax2.plot(epochs_range, relu_val_loss, 'r-s', linewidth=2,
         markersize=4, label='Validation Loss', color='#F44336')
ax2.set_title('Loss over Epochs', fontsize=14, fontweight='bold')
ax2.set_xlabel('Epoch', fontsize=12)
ax2.set_ylabel('Loss', fontsize=12)
ax2.legend(fontsize=11, loc='upper right')
ax2.grid(True, alpha=0.3)
ax2.set_xlim(1, EPOCHS)

plt.tight_layout()
plt.savefig('model_a_relu_performance.png', dpi=150, bbox_inches='tight')
plt.show()
print("✓ Model A (ReLU) plots saved as 'model_a_relu_performance.png'")

# ==========================================
# PLOT SET 2: MODEL B (Sigmoid) - Individual Plots
# ==========================================

fig2, (ax3, ax4) = plt.subplots(1, 2, figsize=(14, 5))
fig2.suptitle('Model B: Sigmoid Activation - Training Progress',
              fontsize=16, fontweight='bold', y=1.02)

# --- Plot 2a: Sigmoid Accuracy ---
ax3.plot(epochs_range, sig_train_acc, 'g-o', linewidth=2,
         markersize=4, label='Training Accuracy', color='#4CAF50')
ax3.plot(epochs_range, sig_val_acc, 'r-s', linewidth=2,
         markersize=4, label='Validation Accuracy', color='#FF9800')
ax3.set_title('Accuracy over Epochs', fontsize=14, fontweight='bold')
ax3.set_xlabel('Epoch', fontsize=12)
ax3.set_ylabel('Accuracy', fontsize=12)
ax3.legend(fontsize=11, loc='lower right')
ax3.grid(True, alpha=0.3)
ax3.set_xlim(1, EPOCHS)
ax3.set_ylim(0.85, 1.0)

# --- Plot 2b: Sigmoid Loss ---
ax4.plot(epochs_range, sig_train_loss, 'g-o', linewidth=2,
         markersize=4, label='Training Loss', color='#4CAF50')
ax4.plot(epochs_range, sig_val_loss, 'r-s', linewidth=2,
         markersize=4, label='Validation Loss', color='#FF9800')
ax4.set_title('Loss over Epochs', fontsize=14, fontweight='bold')
ax4.set_xlabel('Epoch', fontsize=12)
ax4.set_ylabel('Loss', fontsize=12)
ax4.legend(fontsize=11, loc='upper right')
ax4.grid(True, alpha=0.3)
ax4.set_xlim(1, EPOCHS)

plt.tight_layout()
plt.savefig('model_b_sigmoid_performance.png', dpi=150, bbox_inches='tight')
plt.show()
print("✓ Model B (Sigmoid) plots saved as 'model_b_sigmoid_performance.png'")

# ==========================================
# PLOT SET 3: COMBINED COMPARISON PLOTS
# ==========================================
# Side-by-side comparison makes differences immediately visible.

fig3, axes = plt.subplots(2, 2, figsize=(16, 12))
fig3.suptitle('Comparative Analysis: ReLU vs Sigmoid Activation Functions',
              fontsize=18, fontweight='bold')

# --- Plot 3a: Training Accuracy Comparison ---
axes[0, 0].plot(epochs_range, relu_train_acc, 'b-o', linewidth=2,
                markersize=4, label='ReLU - Training')
axes[0, 0].plot(epochs_range, sig_train_acc, 'g-s', linewidth=2,
                markersize=4, label='Sigmoid - Training')
axes[0, 0].set_title('Training Accuracy Comparison', fontsize=14, fontweight='bold')
axes[0, 0].set_xlabel('Epoch', fontsize=12)
axes[0, 0].set_ylabel('Accuracy', fontsize=12)
axes[0, 0].legend(fontsize=11)
axes[0, 0].grid(True, alpha=0.3)
axes[0, 0].set_xlim(1, EPOCHS)

# --- Plot 3b: Validation Accuracy Comparison ---
axes[0, 1].plot(epochs_range, relu_val_acc, 'b-o', linewidth=2,
                markersize=4, label='ReLU - Validation')
axes[0, 1].plot(epochs_range, sig_val_acc, 'g-s', linewidth=2,
                markersize=4, label='Sigmoid - Validation')
axes[0, 1].set_title('Validation Accuracy Comparison', fontsize=14, fontweight='bold')
axes[0, 1].set_xlabel('Epoch', fontsize=12)
axes[0, 1].set_ylabel('Accuracy', fontsize=12)
axes[0, 1].legend(fontsize=11)
axes[0, 1].grid(True, alpha=0.3)
axes[0, 1].set_xlim(1, EPOCHS)

# --- Plot 3c: Training Loss Comparison ---
axes[1, 0].plot(epochs_range, relu_train_loss, 'b-o', linewidth=2,
                markersize=4, label='ReLU - Training')
axes[1, 0].plot(epochs_range, sig_train_loss, 'g-s', linewidth=2,
                markersize=4, label='Sigmoid - Training')
axes[1, 0].set_title('Training Loss Comparison', fontsize=14, fontweight='bold')
axes[1, 0].set_xlabel('Epoch', fontsize=12)
axes[1, 0].set_ylabel('Loss', fontsize=12)
axes[1, 0].legend(fontsize=11)
axes[1, 0].grid(True, alpha=0.3)
axes[1, 0].set_xlim(1, EPOCHS)

# --- Plot 3d: Validation Loss Comparison ---
axes[1, 1].plot(epochs_range, relu_val_loss, 'b-o', linewidth=2,
                markersize=4, label='ReLU - Validation')
axes[1, 1].plot(epochs_range, sig_val_loss, 'g-s', linewidth=2,
                markersize=4, label='Sigmoid - Validation')
axes[1, 1].set_title('Validation Loss Comparison', fontsize=14, fontweight='bold')
axes[1, 1].set_xlabel('Epoch', fontsize=12)
axes[1, 1].set_ylabel('Loss', fontsize=12)
axes[1, 1].legend(fontsize=11)
axes[1, 1].grid(True, alpha=0.3)
axes[1, 1].set_xlim(1, EPOCHS)

plt.tight_layout()
plt.savefig('comparison_relu_vs_sigmoid.png', dpi=150, bbox_inches='tight')
plt.show()
print("✓ Comparison plots saved as 'comparison_relu_vs_sigmoid.png'")

# =====================================================================
# STEP 8: VISUALIZE SOME PREDICTIONS
# =====================================================================
# Let's see what each model actually predicts for some test images.

print("\n>>> STEP 8: Visualizing Sample Predictions...")
print("-" * 60)

# Get predictions from both models
predictions_relu = model_relu.predict(x_test_flat[:10], verbose=0)
predictions_sigmoid = model_sigmoid.predict(x_test_flat[:10], verbose=0)

# Convert probability arrays to single digit predictions
pred_labels_relu = np.argmax(predictions_relu, axis=1)
pred_labels_sigmoid = np.argmax(predictions_sigmoid, axis=1)

fig4, axes = plt.subplots(2, 5, figsize=(15, 7))
fig4.suptitle('Sample Test Predictions', fontsize=16, fontweight='bold')

for i, ax in enumerate(axes.flat):
    ax.imshow(x_test[i], cmap='gray')
    true_label = y_test_original[i]
    relu_pred = pred_labels_relu[i]
    sig_pred = pred_labels_sigmoid[i]

    # Color code: green = correct, red = wrong
    relu_color = 'green' if relu_pred == true_label else 'red'
    sig_color = 'green' if sig_pred == true_label else 'red'

    ax.set_title(
        f'True: {true_label}\n'
        f'ReLU: {relu_pred} | Sig: {sig_pred}',
        fontsize=10,
        color='black'
    )
    ax.axis('off')

plt.tight_layout()
plt.savefig('sample_predictions.png', dpi=150, bbox_inches='tight')
plt.show()
print("✓ Sample predictions saved as 'sample_predictions.png'")

# =====================================================================
# STEP 9: DETAILED EPOCH-BY-EPOCH COMPARISON TABLE
# =====================================================================
print("\n>>> STEP 9: Detailed Epoch-by-Epoch Metrics...")
print("-" * 60)

print(f"\n{'Epoch':>5} | {'--- ReLU ---':>30} | {'--- Sigmoid ---':>30}")
print(f"{'':>5} | {'Train Acc':>10} {'Val Acc':>10} {'Val Loss':>10} | "
      f"{'Train Acc':>10} {'Val Acc':>10} {'Val Loss':>10}")
print("-" * 85)

for i in range(EPOCHS):
    print(f"{i+1:>5} | "
          f"{relu_train_acc[i]:>10.4f} {relu_val_acc[i]:>10.4f} {relu_val_loss[i]:>10.4f} | "
          f"{sig_train_acc[i]:>10.4f} {sig_val_acc[i]:>10.4f} {sig_val_loss[i]:>10.4f}")

# =====================================================================
# STEP 10: COMPARATIVE ANALYSIS AND DISCUSSION
# =====================================================================

print("\n" + "=" * 70)
print("           COMPARATIVE ANALYSIS: ReLU vs Sigmoid")
print("=" * 70)

# Calculate key metrics for comparison
relu_best_val_acc = max(relu_val_acc)
sig_best_val_acc = max(sig_val_acc)
relu_best_epoch = relu_val_acc.index(relu_best_val_acc) + 1
sig_best_epoch = sig_val_acc.index(sig_best_val_acc) + 1

relu_final_train_acc = relu_train_acc[-1]
sig_final_train_acc = sig_train_acc[-1]

# Find epoch where each model first exceeds 95% validation accuracy
relu_95_epoch = next((i+1 for i, acc in enumerate(relu_val_acc) if acc >= 0.95), None)
sig_95_epoch = next((i+1 for i, acc in enumerate(sig_val_acc) if acc >= 0.95), None)

analysis = f"""
╔══════════════════════════════════════════════════════════════════════╗
║                    PERFORMANCE SUMMARY                              ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║  METRIC                        ReLU          Sigmoid                 ║
║  ─────────────────────────────────────────────────────────           ║
║  Final Test Accuracy:      {test_acc_relu*100:>8.2f}%      {test_acc_sigmoid*100:>8.2f}%               ║
║  Final Test Loss:          {test_loss_relu:>8.4f}        {test_loss_sigmoid:>8.4f}               ║
║  Best Validation Accuracy: {relu_best_val_acc*100:>8.2f}%      {sig_best_val_acc*100:>8.2f}%               ║
║  Best Val Acc at Epoch:    {relu_best_epoch:>8d}        {sig_best_epoch:>8d}                  ║
║  Final Training Accuracy:  {relu_final_train_acc*100:>8.2f}%      {sig_final_train_acc*100:>8.2f}%               ║
║  Epoch to reach 95% Val:   {str(relu_95_epoch):>8s}        {str(sig_95_epoch):>8s}                  ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
"""
print(analysis)

# Determine winner
accuracy_diff = (test_acc_relu - test_acc_sigmoid) * 100

discussion = f"""
{'='*70}
ANALYTICAL DISCUSSION
{'='*70}

1. CONVERGENCE SPEED:
   {'─'*50}
   ReLU typically converges FASTER than Sigmoid. This is because:

   • ReLU's gradient is either 0 or 1 (simple computation), allowing
     faster weight updates during backpropagation.

   • Sigmoid's gradient gets very small for large positive or negative
     inputs (values near 0 and 1), causing the "VANISHING GRADIENT"
     problem. This means weights in earlier layers barely change,
     slowing down learning significantly.

   • ReLU reached 95% validation accuracy at epoch {relu_95_epoch if relu_95_epoch else 'N/A'},
     while Sigmoid reached it at epoch {sig_95_epoch if sig_95_epoch else 'N/A'}.

2. FINAL ACCURACY:
   {'─'*50}
   • ReLU achieved {test_acc_relu*100:.2f}% test accuracy.
   • Sigmoid achieved {test_acc_sigmoid*100:.2f}% test accuracy.
   • Difference: {abs(accuracy_diff):.2f}% in favor of {'ReLU' if accuracy_diff > 0 else 'Sigmoid'}.

   ReLU generally achieves higher accuracy because it allows the
   network to learn more complex features. Its non-saturating nature
   means gradients flow freely through the network.

3. LOSS BEHAVIOR:
   {'─'*50}
   • ReLU's loss typically decreases more rapidly and reaches a lower
     final value, indicating better optimization.

   • Sigmoid's loss decreases more slowly and may plateau at a higher
     value due to vanishing gradients limiting learning in deeper layers.

4. OVERFITTING OBSERVATIONS:
   {'─'*50}
   • If training accuracy is much higher than validation accuracy,
     the model is overfitting (memorizing instead of learning).

   • ReLU train-val gap: {abs(relu_final_train_acc - relu_val_acc[-1])*100:.2f}%
   • Sigmoid train-val gap: {abs(sig_final_train_acc - sig_val_acc[-1])*100:.2f}%

5. WHY ReLU IS GENERALLY PREFERRED:
   {'─'*50}
   a) Computational efficiency: max(0, x) is simpler than 1/(1+e^(-x))
   b) No vanishing gradient: Gradient is 1 for positive values
   c) Sparse activation: Some neurons output 0, creating efficient
      representations (like the brain - not all neurons fire at once)
   d) Faster convergence: Reaches good accuracy in fewer epochs

6. WHEN SIGMOID MIGHT STILL BE USEFUL:
   {'─'*50}
   a) Output layer for binary classification (probability 0-1)
   b) Gates in LSTM/GRU recurrent networks
   c) When bounded output (0-1) is specifically needed

CONCLUSION:
{'─'*50}
For this MNIST digit classification task, {'ReLU outperformed Sigmoid'
if accuracy_diff > 0 else 'both performed comparably'}
in terms of convergence speed and final accuracy. This aligns with
modern deep learning best practices where ReLU (or its variants like
Leaky ReLU, ELU) are the default choice for hidden layers in
feed-forward neural networks.
{'='*70}
"""
print(discussion)

# =====================================================================
# BONUS: SAVE MODELS FOR FUTURE USE
# =====================================================================
print(">>> Saving trained models...")
model_relu.save('model_relu_mnist.keras')
model_sigmoid.save('model_sigmoid_mnist.keras')
print("✓ Models saved as 'model_relu_mnist.keras' and 'model_sigmoid_mnist.keras'")

print("\n" + "=" * 70)
print("       PROJECT COMPLETED SUCCESSFULLY!")
print("=" * 70)
print("""
FILES GENERATED:
  1. sample_digits.png              - Sample MNIST images
  2. model_a_relu_performance.png   - ReLU accuracy & loss curves
  3. model_b_sigmoid_performance.png- Sigmoid accuracy & loss curves
  4. comparison_relu_vs_sigmoid.png - Side-by-side comparison
  5. sample_predictions.png         - Model predictions on test images
  6. model_relu_mnist.keras         - Saved ReLU model
  7. model_sigmoid_mnist.keras      - Saved Sigmoid model
""")

